#!/bin/sh

# dpkill – epkill with display isolation
# Copyright © 2014, 2015  Mattias Andrée (maandree@member.fsf.org)
# 
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this library.  If not, see <http://www.gnu.org/licenses/>.

set -e

export THIS_IS_DPKILL=yes

if [ -n "${DISPLAY}" ]; then
    exec epkill =DISPLAY "$@"
else
    echo "${0}: No display found."
fi

exit 1

